# Generated by Django 5.2 on 2025-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "A Fazer"),
                    ("in_progress", "Em Andamento"),
                    ("done", "Concluído"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
